export const DEPLOYED_UPLOAD_URL = 'http://annotationnode-env.eba-iv5i9cmp.us-west-2.elasticbeanstalk.com/api/uploads'
export const DEPLOYED_UPLOAD_UNANNOTATED_URL = 'http://annotationnode-env.eba-iv5i9cmp.us-west-2.elasticbeanstalk.com/api/uploads/unannotated'
export const DEPLOYED_COORDINATE_URL = 'http://annotationnode-env.eba-iv5i9cmp.us-west-2.elasticbeanstalk.com/api/originals'
export const LOCAL_UNANNOTATE = "http://localhost:8080/api/uploads/unannotated"
export const LOCAL_UPLOAD = "http://localhost:8080/api/uploads"
export const DEPLOYED_ORIGINALS_URL = 'http://annotationnode-env.eba-iv5i9cmp.us-west-2.elasticbeanstalk.com/api/originals'
export const LOCAL_COORDINATE = "http://localhost:8080/api/coordinate/"
export const LOCAL_ORIGINAL = "http://localhost:8080/api/originals/"
const PLACEHOLDER = "http://annotationnode-env.eba-iv5i9cmp.us-west-2.elasticbeanstalk.com"
